FROM docker.io/python:3.14.6-trixie
RUN python3 -m pip install ansible-core ansible
WORKDIR /ansible
COPY ansible.cfg homelab.yml hosts.yml node-exporters.yml README.md ./
COPY group_vars roles ./
ENTRYPOINT ["/bin/bash"]
