---
# TODO: This needs to grow as I continue with the homelab, more tasks need to be automated
# Especially backup tasks or recreation tasks

- name: Homelab Configurator
  hosts: all
  collections:
    - containers.podman.podman_container
    - containers.podman.podman_pod
  roles:
    - role: hermes
      host: hermes
      become: true
      become_user: root
      ansible_become_method: su
      when: "'hermes' not in exclude_hosts and inventory_hostname in groups[\"storage\"]"

    - role: poseidon
      host: poseidon
      become: true
      become_user: root
      ansible_become_method: su
      when: "'poseidon' not in exclude_hosts and inventory_hostname in groups[\"media\"]"

    - role: neptune
      host: neptune
      become: true
      become_user: root
      ansible_become_method: su
      when: "'neptune' not in exclude_hosts and inventory_hostname in groups[\"util\"]"
