all:
  hosts:
    ryder:
      ansible_host: 10.69.10.200
      ansible_user: root
      ansible_password: "{{ryder_root_pass}}"
      ansible_become_password: "{{ryder_root_pass}}"
    hermes:
      ansible_host: 10.69.10.201
      ansible_user: "{{hermes_user}}"
      ansible_password: "{{hermes_user_pass}}"
      ansible_become_password: "{{hermes_root_pass}}"
    poseidon:
      ansible_host: 192.168.0.202
      ansible_user: "{{poseidon_user}}"
      ansible_password: "{{poseidon_user_pass}}"
      ansible_become_password: "{{poseidon_root_pass}}"
    neptune:
      ansible_host: 10.69.10.204
      ansible_user: "{{poseidon_user}}"
      ansible_password: "{{poseidon_user_pass}}"
      ansible_become_password: "{{poseidon_root_pass}}"
    oreo:
      ansible_host: 10.69.10.220
      ansible_user: root
      ansible_password: "{{oreo_root_pass}}"
      ansible_become_password: "{{oreo_root_pass}}"
    saturn:
      ansible_host: 10.69.10.221
      ansible_user: "{{saturn_user}}"
      ansible_password: "{{saturn_user_pass }}"
      ansible_become_password: "{{saturn_root_pass}}"
    minerva:
      ansible_host: 10.69.10.222
      ansible_user: "{{minerva_user}}"
      ansible_password: "{{minerva_user_pass }}"
      ansible_become_password: "{{minerva_root_pass}}"

storage:
  hosts:
    hermes:
  # vars:

media:
  hosts:
    poseidon:
  # vars:

util:
  hosts:
    neptune:
  vars:

gpu:
  hosts:
    ryder:

hypervisors:
  hosts:
    ryder:
    oreo:
