all:
  hosts:
    hermes:
    poseidon:
    neptune:

storage:
  hosts:
    hermes:
  vars:
    ansible_host: 192.168.0.201
    ansible_user: "{{hermes_user}}"
    ansible_password: "{{hermes_user_pass}}"
    ansible_become_password: "{{hermes_root_pass}}"

media:
  hosts:
    poseidon:
  vars:
    ansible_host: 192.168.0.202
    ansible_user: "{{poseidon_user}}"
    ansible_password: "{{poseidon_user_pass}}"
    ansible_become_password: "{{poseidon_root_pass}}"

util:
  hosts:
    neptune:
  vars:
    ansible_host: 192.168.0.168
    ansible_user: "{{poseidon_user}}"
    ansible_password: "{{poseidon_user_pass}}"
    ansible_become_password: "{{poseidon_root_pass}}"
